In [4]:
# import pandas as pd

# df = pd.read_csv("../Dataset/Breast-Data/Mask2/Post2_M2.csv", sep="\x1b", engine="python")

# df.columns = list(df.columns[:-1]) + ["Label"]


# df.to_csv("../Dataset/Breast-Data/Mask2/Post2_M2.csv", index=False, sep=",")

# print(df.shape)
# display(df.head())

In [ ]:
import nbformat

nb_path = "Pairwise.ipynb"

nb = nbformat.read(nb_path, as_version=4)

if "tags" not in nb.cells[0].metadata:
    nb.cells[0].metadata["tags"] = []

if "parameters" not in nb.cells[0].metadata["tags"]:
    nb.cells[0].metadata["tags"].append("parameters")

nbformat.write(nb, nb_path)

print("Added 'parameters' tag to first cell.")

Added 'parameters' tag to first cell.

In [6]:
# =============================================================================
# PAIRWISE DATASET BUILDER — REPORT LABEL MISMATCHES ONLY
# =============================================================================
# Purpose:
#   - Build pairwise concatenated radiomics datasets.
#   - Align rows by INFO_NameOfRoi.
#   - Prefix feature columns by dataset/modality name.
#   - If labels match, create model-ready pairwise dataset.
#   - If labels mismatch, do NOT randomly choose, do NOT drop, do NOT majority vote.
#   - Only report mismatches and save review files.
# =============================================================================

import os
import re
import itertools
import numpy as np
import pandas as pd
from pathlib import Path

# -----------------------------------------------------------------------------
# 1. Configure input files
# -----------------------------------------------------------------------------

DATASETS = {
    "Pre":   "../Dataset/Breast-Data/Mask1/Pre_M1.csv",
    "Post1": "../Dataset/Breast-Data/Mask1/Post1_M1.csv",
    "Post2": "../Dataset/Breast-Data/Mask1/Post2_M1.csv",
    "T2":    "../Dataset/Breast-Data/Mask1/T2_M1.csv",
    "ADC":   "../Dataset/Breast-Data/Mask1/ADC_M1.csv",
}


OUT_DIR = "output/pairwise_datasets_report_only"
os.makedirs(OUT_DIR, exist_ok=True)

ID_COL = "INFO_NameOfRoi"


# -----------------------------------------------------------------------------
# 2. Helper functions
# -----------------------------------------------------------------------------

def standardize_label_column(df):
    """
    Standardize Label/Lable column name to Label.
    """
    df = df.copy()

    print(df)

    if "Label" not in df.columns and "Lable" in df.columns:
        df = df.rename(columns={"Lable": "Label"})

    if "Label" not in df.columns:
        raise ValueError("No Label or Lable column found.")

    return df


def extract_patient_id_from_roi(roi):
    """
    Extract patient ID from ROI name.
    Example:
        M1_S2_P17_R      -> P17
        M1_S1_P12_R_#1   -> P12
    """
    match = re.search(r"P(\d+)", str(roi))
    return f"P{match.group(1)}" if match else np.nan


def load_and_prepare_dataset(dataset_name, path):
    """
    Load one dataset:
      - standardize label column
      - extract PatientID
      - keep numeric features only
      - prefix feature names
    """
    df = pd.read_csv(path)
    df = standardize_label_column(df)
    if ID_COL not in df.columns:
        raise ValueError(f"{ID_COL} not found in {dataset_name}: {path}")

    df["PatientID"] = df[ID_COL].apply(extract_patient_id_from_roi)

    non_feature_cols = {
        "INFO_PatientName",
        "INFO_NameOfRoi",
        "Unnamed: 2",
        "FEATURE RESULTS",
        "Label",
        "Lable",
        "PatientID",
    }

    candidate_feature_cols = [
        c for c in df.columns
        if c not in non_feature_cols
    ]

    # Convert features to numeric
    X = df[candidate_feature_cols].apply(pd.to_numeric, errors="coerce")

    # Drop columns that are fully non-numeric / empty
    X = X.dropna(axis=1, how="all")

    # Prefix feature names
    X = X.add_prefix(f"{dataset_name}__")

    prepared_df = pd.concat(
        [
            df[[ID_COL, "PatientID", "Label"]].reset_index(drop=True),
            X.reset_index(drop=True)
        ],
        axis=1
    )

    # Check duplicate ROI IDs
    if prepared_df[ID_COL].duplicated().any():
        duplicated = prepared_df.loc[
            prepared_df[ID_COL].duplicated(keep=False),
            ID_COL
        ].tolist()

        raise ValueError(
            f"Duplicate ROI IDs found in {dataset_name}: {duplicated[:10]}"
        )

    return prepared_df


# -----------------------------------------------------------------------------
# 3. Load all datasets
# -----------------------------------------------------------------------------

prepared = {}

for name, path in DATASETS.items():
    prepared[name] = load_and_prepare_dataset(name, path)

    n_samples = prepared[name].shape[0]
    n_features = prepared[name].shape[1] - 3
    n_patients = prepared[name]["PatientID"].nunique()
    class_counts = prepared[name]["Label"].value_counts().to_dict()

    print(
        f"{name}: samples={n_samples}, patients={n_patients}, "
        f"features={n_features}, labels={class_counts}"
    )


# -----------------------------------------------------------------------------
# 4. Build pairwise datasets and report mismatches
# -----------------------------------------------------------------------------

summary_rows = []
mismatch_rows = []

for name_a, name_b in itertools.combinations(prepared.keys(), 2):

    df_a = prepared[name_a].copy()
    df_b = prepared[name_b].copy()

    merged = df_a.merge(
        df_b,
        on=ID_COL,
        how="inner",
        suffixes=(f"_{name_a}", f"_{name_b}")
    )

    label_a_col = f"Label_{name_a}"
    label_b_col = f"Label_{name_b}"

    patient_a_col = f"PatientID_{name_a}"
    patient_b_col = f"PatientID_{name_b}"

    mismatch_mask = merged[label_a_col] != merged[label_b_col]
    n_mismatch = int(mismatch_mask.sum())

    pair_name = f"{name_a}_{name_b}"
    print("\n" + "=" * 80)
    print(f"Pair: {name_a}+{name_b}")
    print(f"Common ROIs: {merged.shape[0]}")
    print(f"Label mismatches: {n_mismatch}")

    # -------------------------------------------------------------------------
    # If mismatch exists: only report; do not create model-ready dataset.
    # -------------------------------------------------------------------------
    if n_mismatch > 0:

        mismatch_df = merged.loc[
            mismatch_mask,
            [
                ID_COL,
                patient_a_col,
                patient_b_col,
                label_a_col,
                label_b_col
            ]
        ].copy()

        mismatch_df.insert(0, "Pair", f"{name_a}+{name_b}")

        mismatch_df = mismatch_df.rename(columns={
            patient_a_col: f"PatientID_{name_a}",
            patient_b_col: f"PatientID_{name_b}",
            label_a_col: f"Label_{name_a}",
            label_b_col: f"Label_{name_b}",
        })

        mismatch_rows.append(mismatch_df)

        # Save review file with both labels and all features
        review_path = os.path.join(
            OUT_DIR,
            f"{pair_name}_M1_pairwise_NEEDS_REVIEW_label_mismatch.csv"
        )

        merged.to_csv(review_path, index=False)

        print("⚠️ Mismatch detected. Model-ready dataset was NOT created.")
        print("Review file saved to:")
        print(review_path)

        display(mismatch_df)

        summary_rows.append({
            "Pair": f"{name_a}+{name_b}",
            "Status": "NEEDS_REVIEW_LABEL_MISMATCH",
            "n_common_roi": merged.shape[0],
            "n_label_mismatches": n_mismatch,
            "n_samples_model_ready": 0,
            "model_ready_file": "",
            "review_file": review_path,
        })

        continue

    # -------------------------------------------------------------------------
    # If no mismatch: create model-ready pairwise dataset.
    # -------------------------------------------------------------------------

    merged["PatientID"] = merged[patient_a_col]
    merged["Label"] = merged[label_a_col]

    cols_to_drop = [
        patient_a_col,
        patient_b_col,
        label_a_col,
        label_b_col,
    ]

    merged = merged.drop(columns=cols_to_drop)

    feature_cols = [
        c for c in merged.columns
        if c not in [ID_COL, "PatientID", "Label"]
    ]

    final_df = merged[[ID_COL, "PatientID", "Label"] + feature_cols].copy()

    output_path = os.path.join(
        OUT_DIR,
        f"{pair_name}_M1_pairwise.csv"
    )

    final_df.to_csv(output_path, index=False)

    class_counts = final_df["Label"].value_counts().to_dict()

    print("✅ No mismatch. Model-ready pairwise dataset created.")
    print("Saved to:")
    print(output_path)

    summary_rows.append({
        "Pair": f"{name_a}+{name_b}",
        "Status": "MODEL_READY",
        "n_common_roi": merged.shape[0],
        "n_label_mismatches": 0,
        "n_samples_model_ready": final_df.shape[0],
        "n_patients": final_df["PatientID"].nunique(),
        "n_features": len(feature_cols),
        "class_0": class_counts.get(0, class_counts.get("0", 0)),
        "class_1": class_counts.get(1, class_counts.get("1", 0)),
        "model_ready_file": output_path,
        "review_file": "",
    })


# -----------------------------------------------------------------------------
# 5. Save reports
# -----------------------------------------------------------------------------

df_pairwise_summary = pd.DataFrame(summary_rows)

summary_path = os.path.join(
    OUT_DIR,
    "pairwise_summary_report_only.csv"
)

df_pairwise_summary.to_csv(summary_path, index=False)

if len(mismatch_rows) > 0:
    df_label_mismatch_report = pd.concat(mismatch_rows, ignore_index=True)
else:
    df_label_mismatch_report = pd.DataFrame(
        columns=[
            "Pair",
            ID_COL,
            "PatientID_A",
            "PatientID_B",
            "Label_A",
            "Label_B",
        ]
    )

mismatch_report_path = os.path.join(
    OUT_DIR,
    "label_mismatch_report_only.csv"
)

df_label_mismatch_report.to_csv(mismatch_report_path, index=False)

print("\n" + "=" * 80)
print("PAIRWISE CONCATENATION FINISHED")
print("=" * 80)

print("Summary saved to:")
print(summary_path)

print("Mismatch report saved to:")
print(mismatch_report_path)

print("\nSummary:")
display(df_pairwise_summary)

print("\nMismatch report:")
display(df_label_mismatch_report)

    INFO_PatientName  INFO_NameOfRoi  Unnamed: 2  \
0           Pre_D_P1   M1_S2_P1_R_#1         NaN
1           Pre_D_P1   M1_S1_P1_R_#1         NaN
2           Pre_D_P1   M1_S3_P1_R_#1         NaN
3           Pre_D_P1   M1_S5_P1_R_#1         NaN
4           Pre_D_P1   M1_S4_P1_R_#1         NaN
..               ...             ...         ...
112        Pre_D_P50  M1_S8_P50_L_#1         NaN
113         Pre_D_P6      M1_S2_P6_R         NaN
114         Pre_D_P6      M1_S1_P6_L         NaN
115        Pre_D_P17     M1_S1_P17_L         NaN
116        Pre_D_P17     M1_S2_P17_R         NaN

     MORPHOLOGICAL_Volume(IBSI:RNU0)[cm3]  \
0                                1.074417
1                                9.876958
2                                0.187583
3                                0.192417
4                                0.073667
..                                    ...
112                              0.186083
113                              0.071875
114                              0.071875
115                              1.236833
116                              0.526625

     MORPHOLOGICAL_ApproximateVolume(IBSI:YEKZ)[cm3]  \
0                                              1.090
1                                              9.909
2                                              0.196
3                                              0.202
4                                              0.082
..                                               ...
112                                            0.194
113                                            0.077
114                                            0.077
115                                            1.253
116                                            0.539

     MORPHOLOGICAL_voxelsCounting(IBSI:No)[#vx]  \
0                                          1090
1                                          9909
2                                           196
3                                           202
4                                            82
..                                          ...
112                                         194
113                                          77
114                                          77
115                                        1253
116                                         539

     MORPHOLOGICAL_SurfaceArea(IBSI:C0JK)[cm2]  \
0                                     7.079835
1                                    29.855902
2                                     2.043052
3                                     2.246322
4                                     1.787012
..                                         ...
112                                   1.929539
113                                   1.005097
114                                   0.970422
115                                   7.386230
116                                   4.185875

     MORPHOLOGICAL_SurfaceToVolumeRatio(IBSI:2PR5)[cm]  \
0                                             6.589469
1                                             3.022783
2                                            10.891437
3                                            11.674260
4                                            24.258075
..                                                 ...
112                                          10.369220
113                                          13.983964
114                                          13.501529
115                                           5.971888
116                                           7.948492

     MORPHOLOGICAL_Compacity(IBSI:No)[]  \
0                             17.533231
1                             16.516654
2                             15.567716
3                             17.497073
4                             32.427989
..                                  ...
112                           14.403660
113                           14.019559
114                           13.300358
115                           16.230171
116                           16.262146

     MORPHOLOGICAL_Compactness1(IBSI:SKGS)[]  ...  \
0                                   0.032178  ...
1                                   0.034159  ...
2                                   0.036241  ...
3                                   0.032245  ...
4                                   0.017398  ...
..                                       ...  ...
112                                 0.039170  ...
113                                 0.040243  ...
114                                 0.042419  ...
115                                 0.034762  ...
116                                 0.034693  ...

     GLSZM_LargeZoneHighGreyLevelEmphasis(IBSI:J17V)  \
0                                       5.048857e+04
1                                       3.217510e+06
2                                       5.750794e+03
3                                       2.432606e+04
4                                       1.516655e+03
..                                               ...
112                                     4.184000e+03
113                                     1.112051e+03
114                                     4.147250e+03
115                                     1.161347e+05
116                                     4.920081e+04

     GLSZM_GreyLevelNonUniformity(IBSI:JNSA)  \
0                                  10.527132
1                                  44.866931
2                                   3.882353
3                                   3.416667
4                                   3.000000
..                                       ...
112                                 3.656250
113                                 2.230769
114                                 2.333333
115                                12.623932
116                                 6.555556

     GLSZM_NormalisedGreyLevelNonUniformity(IBSI:Y1RO)  \
0                                             0.040803
1                                             0.044555
2                                             0.057093
3                                             0.071181
4                                             0.054545
..                                                 ...
112                                           0.057129
113                                           0.057199
114                                           0.097222
115                                           0.107897
116                                           0.060700

     GLSZM_ZoneSizeNonUniformity(IBSI:4JP3)  \
0                                 75.976744
1                                244.813307
2                                 17.794118
3                                 11.708333
4                                 29.945455
..                                      ...
112                               16.343750
113                               14.641026
114                                4.916667
115                               26.230769
116                               30.703704

     GLSZM_NormalisedZoneSizeNonUniformity(IBSI:VB3A)  \
0                                            0.294484
1                                            0.243112
2                                            0.261678
3                                            0.243924
4                                            0.544463
..                                                ...
112                                          0.255371
113                                          0.375411
114                                          0.204861
115                                          0.224195
116                                          0.284294

     GLSZM_ZonePercentage(IBSI:P30P)  GLSZM_GreyLevelVariance(IBSI:BYLV)  \
0                           0.236697                           50.287257
1                           0.101625                           44.766606
2                           0.346939                           34.000865
3                           0.237624                           24.484375
4                           0.670732                           41.981488
..                               ...                                 ...
112                         0.329897                           33.334961
113                         0.506494                           34.946746
114                         0.311688                           10.609375
115                         0.093376                            8.675141
116                         0.200371                           27.900892

     GLSZM_ZoneSizeVariance(IBSI:3NSA)  GLSZM_ZoneSizeEntropy(IBSI:GU8N)  \
0                           107.050237                          6.437730
1                          9622.090625                          7.083283
2                             8.868512                          5.341067
3                            57.956597                          5.152569
4                             1.195372                          4.912734
..                                 ...                               ...
112                          10.592773                          5.515320
113                           1.153189                          4.670018
114                           7.414931                          4.334963
115                        1687.488202                          5.520320
116                         144.527692                          5.742848

     Label
0        1
1        1
2        1
3        1
4        1
..     ...
112      0
113      0
114      0
115      0
116      0

[117 rows x 149 columns]
Pre: samples=117, patients=48, features=145, labels={1: 65, 0: 52}
    INFO_PatientName  INFO_NameOfRoi  Unnamed: 2  \
0         Post_D1_P1   M1_S2_P1_R_#1         NaN
1         Post_D1_P1   M1_S1_P1_R_#1         NaN
2         Post_D1_P1   M1_S4_P1_R_#1         NaN
3         Post_D1_P1   M1_S3_P1_R_#1         NaN
4         Post_D1_P1   M1_S5_P1_R_#1         NaN
..               ...             ...         ...
111      Post_D1_P50  M1_S3_P50_R_#1         NaN
112      Post_D1_P17     M1_S2_P17_R         NaN
113      Post_D1_P17     M1_S1_P17_L         NaN
114       Post_D1_P6      M1_S1_P6_L         NaN
115       Post_D1_P6      M1_S2_P6_R         NaN

     MORPHOLOGICAL_Volume(IBSI:RNU0)[cm3]  \
0                                1.074417
1                                9.876958
2                                0.073667
3                                0.187583
4                                0.192417
..                                    ...
111                              0.116917
112                              0.526625
113                              1.236833
114                              0.071875
115                              0.071875

     MORPHOLOGICAL_ApproximateVolume(IBSI:YEKZ)[cm3]  \
0                                              1.090
1                                              9.909
2                                              0.082
3                                              0.196
4                                              0.202
..                                               ...
111                                            0.124
112                                            0.539
113                                            1.253
114                                            0.077
115                                            0.077

     MORPHOLOGICAL_voxelsCounting(IBSI:No)[#vx]  \
0                                          1090
1                                          9909
2                                            82
3                                           196
4                                           202
..                                          ...
111                                         124
112                                         539
113                                        1253
114                                          77
115                                          77

     MORPHOLOGICAL_SurfaceArea(IBSI:C0JK)[cm2]  \
0                                     7.079835
1                                    29.855902
2                                     1.787012
3                                     2.043052
4                                     2.246322
..                                         ...
111                                   1.520306
112                                   4.185875
113                                   7.386230
114                                   0.970422
115                                   1.005097

     MORPHOLOGICAL_SurfaceToVolumeRatio(IBSI:2PR5)[cm]  \
0                                             6.589469
1                                             3.022783
2                                            24.258075
3                                            10.891437
4                                            11.674260
..                                                 ...
111                                          13.003326
112                                           7.948492
113                                           5.971888
114                                          13.501529
115                                          13.983964

     MORPHOLOGICAL_Compacity(IBSI:No)[]  \
0                             17.533231
1                             16.516654
2                             32.427989
3                             15.567716
4                             17.497073
..                                  ...
111                           16.033188
112                           16.262146
113                           16.230171
114                           13.300358
115                           14.019559

     MORPHOLOGICAL_Compactness1(IBSI:SKGS)[]  ...  \
0                                   0.032178  ...
1                                   0.034159  ...
2                                   0.017398  ...
3                                   0.036241  ...
4                                   0.032245  ...
..                                       ...  ...
111                                 0.035189  ...
112                                 0.034693  ...
113                                 0.034762  ...
114                                 0.042419  ...
115                                 0.040243  ...

     GLSZM_LargeZoneHighGreyLevelEmphasis(IBSI:J17V)  \
0                                       5.045927e+04
1                                       3.374866e+06
2                                       1.026723e+03
3                                       7.142796e+03
4                                       7.745821e+03
..                                               ...
111                                     2.044000e+03
112                                     4.603624e+04
113                                     5.854572e+04
114                                     3.260095e+03
115                                     1.037629e+03

     GLSZM_GreyLevelNonUniformity(IBSI:JNSA)  \
0                                  11.333333
1                                  44.910791
2                                   3.297872
3                                   3.367347
4                                   3.428571
..                                       ...
111                                 2.600000
112                                 5.873239
113                                15.800000
114                                 2.333333
115                                 2.085714

     GLSZM_NormalisedGreyLevelNonUniformity(IBSI:Y1RO)  \
0                                             0.059028
1                                             0.064620
2                                             0.070167
3                                             0.068721
4                                             0.061224
..                                                 ...
111                                           0.047273
112                                           0.082722
113                                           0.158000
114                                           0.111111
115                                           0.059592

     GLSZM_ZoneSizeNonUniformity(IBSI:4JP3)  \
0                                 49.083333
1                                157.656115
2                                 19.893617
3                                 12.061224
4                                 14.607143
..                                      ...
111                               17.909091
112                               14.323944
113                               20.440000
114                                3.857143
115                               11.571429

     GLSZM_NormalisedZoneSizeNonUniformity(IBSI:VB3A)  \
0                                            0.255642
1                                            0.226843
2                                            0.423268
3                                            0.246147
4                                            0.260842
..                                                ...
111                                          0.325620
112                                          0.201746
113                                          0.204400
114                                          0.183673
115                                          0.330612

     GLSZM_ZonePercentage(IBSI:P30P)  GLSZM_GreyLevelVariance(IBSI:BYLV)  \
0                           0.176147                           22.603733
1                           0.070138                           21.239327
2                           0.573171                           22.828429
3                           0.250000                           20.857143
4                           0.277228                           29.849171
..                               ...                                 ...
111                         0.443548                           56.381488
112                         0.131725                           14.576870
113                         0.079808                            4.347500
114                         0.272727                            8.521542
115                         0.454545                           37.996735

     GLSZM_ZoneSizeVariance(IBSI:3NSA)  GLSZM_ZoneSizeEntropy(IBSI:GU8N)  \
0                           222.781141                          6.085247
1                         20862.850210                          6.625768
2                             1.551833                          4.953213
3                            31.224490                          4.956247
4                            24.274235                          5.351823
..                                 ...                               ...
111                           1.498843                          5.267457
112                         242.100774                          5.364192
113                        3213.729100                          5.092922
114                           7.650794                          4.201841
115                           3.360000                          4.843569

     Label
0        1
1        1
2        1
3        1
4        1
..     ...
111      1
112      0
113      0
114      0
115      0

[116 rows x 149 columns]
Post1: samples=116, patients=48, features=145, labels={1: 64, 0: 52}
    INFO_PatientName  INFO_NameOfRoi  Unnamed: 2  \
0         Post_D2_P1   M1_S1_P1_R_#1         NaN
1         Post_D2_P1   M1_S2_P1_R_#1         NaN
2         Post_D2_P1   M1_S5_P1_R_#1         NaN
3         Post_D2_P1   M1_S3_P1_R_#1         NaN
4         Post_D2_P1   M1_S4_P1_R_#1         NaN
..               ...             ...         ...
112      Post_D2_P50  M1_S2_P50_R_#1         NaN
113      Post_D2_P17     M1_S2_P17_R         NaN
114      Post_D2_P17     M1_S1_P17_L         NaN
115       Post_D2_P6      M1_S2_P6_R         NaN
116       Post_D2_P6      M1_S1_P6_L         NaN

     MORPHOLOGICAL_Volume(IBSI:RNU0)[cm3]  \
0                                9.876958

,Pair,Status,n_common_roi,n_label_mismatches,n_samples_model_ready,n_patients,n_features,class_0,class_1,model_ready_file,review_file
0,Pre+Post1,MODEL_READY,116,0,116,48,290,52,64,output/pairwise_datasets_report_only/Pre_Post1...,
1,Pre+Post2,MODEL_READY,117,0,117,48,290,52,65,output/pairwise_datasets_report_only/Pre_Post2...,
2,Pre+T2,MODEL_READY,117,0,117,48,290,52,65,output/pairwise_datasets_report_only/Pre_T2_M1...,
3,Pre+ADC,MODEL_READY,114,0,114,48,289,50,64,output/pairwise_datasets_report_only/Pre_ADC_M...,
4,Post1+Post2,MODEL_READY,116,0,116,48,290,52,64,output/pairwise_datasets_report_only/Post1_Pos...,
5,Post1+T2,MODEL_READY,116,0,116,48,290,52,64,output/pairwise_datasets_report_only/Post1_T2_...,
6,Post1+ADC,MODEL_READY,113,0,113,48,289,50,63,output/pairwise_datasets_report_only/Post1_ADC...,
7,Post2+T2,MODEL_READY,117,0,117,48,290,52,65,output/pairwise_datasets_report_only/Post2_T2_...,
8,Post2+ADC,MODEL_READY,114,0,114,48,289,50,64,output/pairwise_datasets_report_only/Post2_ADC...,
9,T2+ADC,MODEL_READY,114,0,114,48,289,50,64,output/pairwise_datasets_report_only/T2_ADC_M1...,

Mismatch report:

Empty DataFrame
Columns: [Pair, INFO_NameOfRoi, PatientID_A, PatientID_B, Label_A, Label_B]
Index: []

In [7]:
import os
import glob
from pathlib import Path

try:
    import papermill as pm
except ImportError:
    !pip install -q papermill
    import papermill as pm

TEMPLATE_NOTEBOOK = "Main_Pairwise.ipynb"

PAIRWISE_DIR = "output/pairwise_datasets_report_only"

BATCH_ROOT = "./nested_cv_outputs_pairwise_batch"
EXECUTED_NOTEBOOK_DIR = "./executed_pairwise_notebooks"

os.makedirs(BATCH_ROOT, exist_ok=True)
os.makedirs(EXECUTED_NOTEBOOK_DIR, exist_ok=True)

pairwise_files = sorted(
    glob.glob(os.path.join(PAIRWISE_DIR, "*_M1_pairwise.csv"))
)

print("Found pairwise datasets:", len(pairwise_files))
for f in pairwise_files:
    print(" -", f)

completed_runs = []
failed_runs = []

for input_file in pairwise_files:
    
    dataset_tag = Path(input_file).stem.replace("_M1_pairwise", "")
    
    output_notebook = os.path.join(
        EXECUTED_NOTEBOOK_DIR,
        f"{dataset_tag}_executed.ipynb"
    )
    
    print("\n" + "=" * 100)
    print("Running:", dataset_tag)
    print("Input:", input_file)
    print("Executed notebook:", output_notebook)
    print("=" * 100)
    
    try:
        pm.execute_notebook(
            input_path=TEMPLATE_NOTEBOOK,
            output_path=output_notebook,
            parameters={
                "INPUT_FILE": input_file,
                "DATASET_TAG": dataset_tag,
                "BATCH_ROOT": BATCH_ROOT,
                "OUTPUT_DIR": f"./output/cleaned_pairwise/{dataset_tag}",
            },
            kernel_name="python3",
            progress_bar=True,
            log_output=True,
        )
        
        completed_runs.append(dataset_tag)
        print("DONE:", dataset_tag)
        
    except Exception as e:
        failed_runs.append({
            "dataset": dataset_tag,
            "input_file": input_file,
            "error": str(e)
        })
        print("FAILED:", dataset_tag)
        print(e)

print("\nBATCH FINISHED")
print("Completed:", completed_runs)
print("Failed:", failed_runs)

Found pairwise datasets: 10
 - output/pairwise_datasets_report_only/Post1_ADC_M1_pairwise.csv
 - output/pairwise_datasets_report_only/Post1_Post2_M1_pairwise.csv
 - output/pairwise_datasets_report_only/Post1_T2_M1_pairwise.csv
 - output/pairwise_datasets_report_only/Post2_ADC_M1_pairwise.csv
 - output/pairwise_datasets_report_only/Post2_T2_M1_pairwise.csv
 - output/pairwise_datasets_report_only/Pre_ADC_M1_pairwise.csv
 - output/pairwise_datasets_report_only/Pre_Post1_M1_pairwise.csv
 - output/pairwise_datasets_report_only/Pre_Post2_M1_pairwise.csv
 - output/pairwise_datasets_report_only/Pre_T2_M1_pairwise.csv
 - output/pairwise_datasets_report_only/T2_ADC_M1_pairwise.csv

====================================================================================================
Running: Post1_ADC
Input: output/pairwise_datasets_report_only/Post1_ADC_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/Post1_ADC_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

PermutationExplainer explainer: 100%|██████████| 113/113 [00:00<?, ?it/s]
PermutationExplainer explainer: 114it [00:10, 10.09s/it]

DONE: Post1_ADC

====================================================================================================
Running: Post1_Post2
Input: output/pairwise_datasets_report_only/Post1_Post2_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/Post1_Post2_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

DONE: Post1_Post2

====================================================================================================
Running: Post1_T2
Input: output/pairwise_datasets_report_only/Post1_T2_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/Post1_T2_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

DONE: Post1_T2

====================================================================================================
Running: Post2_ADC
Input: output/pairwise_datasets_report_only/Post2_ADC_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/Post2_ADC_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

DONE: Post2_ADC

====================================================================================================
Running: Post2_T2
Input: output/pairwise_datasets_report_only/Post2_T2_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/Post2_T2_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

PermutationExplainer explainer:  66%|██████▌   | 77/117 [00:00<?, ?it/s]
PermutationExplainer explainer:  68%|██████▊   | 79/117 [00:10<00:03, 12.36it/s]
PermutationExplainer explainer:  69%|██████▉   | 81/117 [00:10<00:03,  9.50it/s]
PermutationExplainer explainer:  70%|███████   | 82/117 [00:10<00:03,  9.07it/s]
PermutationExplainer explainer:  71%|███████   | 83/117 [00:10<00:03,  9.05it/s]
PermutationExplainer explainer:  72%|███████▏  | 84/117 [00:10<00:03,  8.77it/s]
PermutationExplainer explainer:  73%|███████▎  | 85/117 [00:10<00:03,  8.84it/s]
PermutationExplainer explainer:  74%|███████▎  | 86/117 [00:11<00:03,  8.89it/s]
PermutationExplainer explainer:  74%|███████▍  | 87/117 [00:11<00:03,  8.71it/s]
PermutationExplainer explainer:  75%|███████▌  | 88/117 [00:11<00:03,  8.68it/s]
PermutationExplainer explainer:  76%|███████▌  | 89/117 [00:11<00:03,  8.69it/s]
PermutationExplainer explainer:  77%|███████▋  | 90/117 [00:11<00:03,  8.70it/s]
PermutationExplainer explainer:  78%|███████▊  | 91/117 [00:11<00:02,  8.69it/s]
PermutationExplainer explainer:  79%|███████▊  | 92/117 [00:11<00:02,  8.56it/s]
PermutationExplainer explainer:  79%|███████▉  | 93/117 [00:11<00:02,  8.65it/s]
PermutationExplainer explainer:  80%|████████  | 94/117 [00:11<00:02,  8.65it/s]
PermutationExplainer explainer:  81%|████████  | 95/117 [00:12<00:02,  8.78it/s]
PermutationExplainer explainer:  82%|████████▏ | 96/117 [00:12<00:02,  8.89it/s]
PermutationExplainer explainer:  83%|████████▎ | 97/117 [00:12<00:02,  8.79it/s]
PermutationExplainer explainer:  84%|████████▍ | 98/117 [00:12<00:02,  8.96it/s]
PermutationExplainer explainer:  85%|████████▍ | 99/117 [00:12<00:01,  9.16it/s]
PermutationExplainer explainer:  85%|████████▌ | 100/117 [00:12<00:01,  9.26it/s]
PermutationExplainer explainer:  86%|████████▋ | 101/117 [00:12<00:01,  9.29it/s]
PermutationExplainer explainer:  87%|████████▋ | 102/117 [00:12<00:01,  8.91it/s]
PermutationExplainer explainer:  88%|████████▊ | 103/117 [00:12<00:01,  8.92it/s]
PermutationExplainer explainer:  89%|████████▉ | 104/117 [00:13<00:01,  8.82it/s]
PermutationExplainer explainer:  90%|████████▉ | 105/117 [00:13<00:01,  8.84it/s]
PermutationExplainer explainer:  91%|█████████ | 106/117 [00:13<00:01,  8.79it/s]
PermutationExplainer explainer:  91%|█████████▏| 107/117 [00:13<00:01,  8.75it/s]
PermutationExplainer explainer:  92%|█████████▏| 108/117 [00:13<00:01,  8.65it/s]
PermutationExplainer explainer:  93%|█████████▎| 109/117 [00:13<00:00,  8.81it/s]
PermutationExplainer explainer:  94%|█████████▍| 110/117 [00:13<00:00,  8.89it/s]
PermutationExplainer explainer:  95%|█████████▍| 111/117 [00:13<00:00,  9.06it/s]
PermutationExplainer explainer:  96%|█████████▌| 112/117 [00:13<00:00,  9.16it/s]
PermutationExplainer explainer:  97%|█████████▋| 113/117 [00:14<00:00,  8.85it/s]
PermutationExplainer explainer:  97%|█████████▋| 114/117 [00:14<00:00,  8.82it/s]
PermutationExplainer explainer:  98%|█████████▊| 115/117 [00:14<00:00,  8.81it/s]
PermutationExplainer explainer:  99%|█████████▉| 116/117 [00:14<00:00,  8.99it/s]
PermutationExplainer explainer: 100%|██████████| 117/117 [00:14<00:00,  9.01it/s]
PermutationExplainer explainer: 118it [00:14,  8.88it/s]
PermutationExplainer explainer: 118it [00:14,  2.79it/s]

DONE: Post2_T2

====================================================================================================
Running: Pre_ADC
Input: output/pairwise_datasets_report_only/Pre_ADC_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/Pre_ADC_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

DONE: Pre_ADC

====================================================================================================
Running: Pre_Post1
Input: output/pairwise_datasets_report_only/Pre_Post1_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/Pre_Post1_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

DONE: Pre_Post1

====================================================================================================
Running: Pre_Post2
Input: output/pairwise_datasets_report_only/Pre_Post2_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/Pre_Post2_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

PermutationExplainer explainer:  49%|████▊     | 57/117 [00:00<?, ?it/s]
PermutationExplainer explainer:  50%|█████     | 59/117 [00:10<00:04, 13.17it/s]
PermutationExplainer explainer:  52%|█████▏    | 61/117 [00:10<00:06,  8.70it/s]
PermutationExplainer explainer:  53%|█████▎    | 62/117 [00:10<00:06,  8.12it/s]
PermutationExplainer explainer:  54%|█████▍    | 63/117 [00:10<00:06,  7.74it/s]
PermutationExplainer explainer:  55%|█████▍    | 64/117 [00:10<00:07,  7.46it/s]
PermutationExplainer explainer:  56%|█████▌    | 65/117 [00:11<00:07,  7.28it/s]
PermutationExplainer explainer:  56%|█████▋    | 66/117 [00:11<00:07,  7.17it/s]
PermutationExplainer explainer:  57%|█████▋    | 67/117 [00:11<00:07,  7.12it/s]
PermutationExplainer explainer:  58%|█████▊    | 68/117 [00:11<00:06,  7.04it/s]
PermutationExplainer explainer:  59%|█████▉    | 69/117 [00:11<00:06,  6.99it/s]
PermutationExplainer explainer:  60%|█████▉    | 70/117 [00:11<00:06,  6.92it/s]
PermutationExplainer explainer:  61%|██████    | 71/117 [00:12<00:06,  6.92it/s]
PermutationExplainer explainer:  62%|██████▏   | 72/117 [00:12<00:06,  6.91it/s]
PermutationExplainer explainer:  62%|██████▏   | 73/117 [00:12<00:06,  6.90it/s]
PermutationExplainer explainer:  63%|██████▎   | 74/117 [00:12<00:06,  6.63it/s]
PermutationExplainer explainer:  64%|██████▍   | 75/117 [00:12<00:06,  6.58it/s]
PermutationExplainer explainer:  65%|██████▍   | 76/117 [00:12<00:06,  6.69it/s]
PermutationExplainer explainer:  66%|██████▌   | 77/117 [00:12<00:05,  6.76it/s]
PermutationExplainer explainer:  67%|██████▋   | 78/117 [00:13<00:05,  6.82it/s]
PermutationExplainer explainer:  68%|██████▊   | 79/117 [00:13<00:05,  6.83it/s]
PermutationExplainer explainer:  68%|██████▊   | 80/117 [00:13<00:05,  6.82it/s]
PermutationExplainer explainer:  69%|██████▉   | 81/117 [00:13<00:05,  6.85it/s]
PermutationExplainer explainer:  70%|███████   | 82/117 [00:13<00:05,  6.69it/s]
PermutationExplainer explainer:  71%|███████   | 83/117 [00:13<00:05,  6.80it/s]
PermutationExplainer explainer:  72%|███████▏  | 84/117 [00:13<00:04,  6.82it/s]
PermutationExplainer explainer:  73%|███████▎  | 85/117 [00:14<00:04,  6.82it/s]
PermutationExplainer explainer:  74%|███████▎  | 86/117 [00:14<00:04,  6.82it/s]
PermutationExplainer explainer:  74%|███████▍  | 87/117 [00:14<00:04,  6.89it/s]
PermutationExplainer explainer:  75%|███████▌  | 88/117 [00:14<00:04,  6.84it/s]
PermutationExplainer explainer:  76%|███████▌  | 89/117 [00:14<00:04,  6.89it/s]
PermutationExplainer explainer:  77%|███████▋  | 90/117 [00:14<00:03,  6.82it/s]
PermutationExplainer explainer:  78%|███████▊  | 91/117 [00:14<00:03,  6.76it/s]
PermutationExplainer explainer:  79%|███████▊  | 92/117 [00:15<00:03,  6.75it/s]
PermutationExplainer explainer:  79%|███████▉  | 93/117 [00:15<00:03,  6.71it/s]
PermutationExplainer explainer:  80%|████████  | 94/117 [00:15<00:03,  6.76it/s]
PermutationExplainer explainer:  81%|████████  | 95/117 [00:15<00:03,  6.74it/s]
PermutationExplainer explainer:  82%|████████▏ | 96/117 [00:15<00:03,  6.75it/s]
PermutationExplainer explainer:  83%|████████▎ | 97/117 [00:15<00:02,  6.78it/s]
PermutationExplainer explainer:  84%|████████▍ | 98/117 [00:15<00:02,  6.82it/s]
PermutationExplainer explainer:  85%|████████▍ | 99/117 [00:16<00:02,  6.85it/s]
PermutationExplainer explainer:  85%|████████▌ | 100/117 [00:16<00:02,  6.86it/s]
PermutationExplainer explainer:  86%|████████▋ | 101/117 [00:16<00:02,  6.84it/s]
PermutationExplainer explainer:  87%|████████▋ | 102/117 [00:16<00:02,  6.84it/s]
PermutationExplainer explainer:  88%|████████▊ | 103/117 [00:16<00:02,  6.94it/s]
PermutationExplainer explainer:  89%|████████▉ | 104/117 [00:16<00:01,  6.93it/s]
PermutationExplainer explainer:  90%|████████▉ | 105/117 [00:17<00:01,  6.92it/s]
PermutationExplainer explainer:  91%|█████████ | 106/117 [00:17<00:01,  6.81it/s]
PermutationExplainer explainer:  91%|█████████▏| 107/117 [00:17<00:01,  6.81it/s]
PermutationExplainer explainer:  92%|█████████▏| 108/117 [00:17<00:01,  6.90it/s]
PermutationExplainer explainer:  93%|█████████▎| 109/117 [00:17<00:01,  6.90it/s]
PermutationExplainer explainer:  94%|█████████▍| 110/117 [00:17<00:01,  6.89it/s]
PermutationExplainer explainer:  95%|█████████▍| 111/117 [00:17<00:00,  6.91it/s]
PermutationExplainer explainer:  96%|█████████▌| 112/117 [00:18<00:00,  6.84it/s]
PermutationExplainer explainer:  97%|█████████▋| 113/117 [00:18<00:00,  6.89it/s]
PermutationExplainer explainer:  97%|█████████▋| 114/117 [00:18<00:00,  6.90it/s]
PermutationExplainer explainer:  98%|█████████▊| 115/117 [00:18<00:00,  6.90it/s]
PermutationExplainer explainer:  99%|█████████▉| 116/117 [00:18<00:00,  6.87it/s]
PermutationExplainer explainer: 100%|██████████| 117/117 [00:18<00:00,  6.85it/s]
PermutationExplainer explainer: 118it [00:18,  6.91it/s]
PermutationExplainer explainer: 118it [00:18,  3.23it/s]

DONE: Pre_Post2

====================================================================================================
Running: Pre_T2
Input: output/pairwise_datasets_report_only/Pre_T2_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/Pre_T2_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

PermutationExplainer explainer:  27%|██▋       | 32/117 [00:00<?, ?it/s]
PermutationExplainer explainer:  29%|██▉       | 34/117 [00:10<00:10,  7.69it/s]
PermutationExplainer explainer:  30%|██▉       | 35/117 [00:10<00:14,  5.51it/s]
PermutationExplainer explainer:  31%|███       | 36/117 [00:10<00:16,  4.80it/s]
PermutationExplainer explainer:  32%|███▏      | 37/117 [00:11<00:17,  4.45it/s]
PermutationExplainer explainer:  32%|███▏      | 38/117 [00:11<00:18,  4.25it/s]
PermutationExplainer explainer:  33%|███▎      | 39/117 [00:11<00:18,  4.11it/s]
PermutationExplainer explainer:  34%|███▍      | 40/117 [00:11<00:18,  4.05it/s]
PermutationExplainer explainer:  35%|███▌      | 41/117 [00:12<00:19,  3.97it/s]
PermutationExplainer explainer:  36%|███▌      | 42/117 [00:12<00:19,  3.94it/s]
PermutationExplainer explainer:  37%|███▋      | 43/117 [00:12<00:18,  3.93it/s]
PermutationExplainer explainer:  38%|███▊      | 44/117 [00:12<00:18,  3.91it/s]
PermutationExplainer explainer:  38%|███▊      | 45/117 [00:13<00:18,  3.90it/s]
PermutationExplainer explainer:  39%|███▉      | 46/117 [00:13<00:18,  3.89it/s]
PermutationExplainer explainer:  40%|████      | 47/117 [00:13<00:18,  3.89it/s]
PermutationExplainer explainer:  41%|████      | 48/117 [00:13<00:17,  3.91it/s]
PermutationExplainer explainer:  42%|████▏     | 49/117 [00:14<00:17,  3.87it/s]
PermutationExplainer explainer:  43%|████▎     | 50/117 [00:14<00:17,  3.88it/s]
PermutationExplainer explainer:  44%|████▎     | 51/117 [00:14<00:17,  3.88it/s]
PermutationExplainer explainer:  44%|████▍     | 52/117 [00:14<00:16,  3.90it/s]
PermutationExplainer explainer:  45%|████▌     | 53/117 [00:15<00:16,  3.90it/s]
PermutationExplainer explainer:  46%|████▌     | 54/117 [00:15<00:16,  3.92it/s]
PermutationExplainer explainer:  47%|████▋     | 55/117 [00:15<00:15,  3.91it/s]
PermutationExplainer explainer:  48%|████▊     | 56/117 [00:15<00:15,  3.87it/s]
PermutationExplainer explainer:  49%|████▊     | 57/117 [00:16<00:15,  3.91it/s]
PermutationExplainer explainer:  50%|████▉     | 58/117 [00:16<00:15,  3.87it/s]
PermutationExplainer explainer:  50%|█████     | 59/117 [00:16<00:14,  3.89it/s]
PermutationExplainer explainer:  51%|█████▏    | 60/117 [00:16<00:14,  3.90it/s]
PermutationExplainer explainer:  52%|█████▏    | 61/117 [00:17<00:14,  3.91it/s]
PermutationExplainer explainer:  53%|█████▎    | 62/117 [00:17<00:14,  3.89it/s]
PermutationExplainer explainer:  54%|█████▍    | 63/117 [00:17<00:13,  3.91it/s]
PermutationExplainer explainer:  55%|█████▍    | 64/117 [00:18<00:13,  3.88it/s]
PermutationExplainer explainer:  56%|█████▌    | 65/117 [00:18<00:13,  3.90it/s]
PermutationExplainer explainer:  56%|█████▋    | 66/117 [00:18<00:13,  3.89it/s]
PermutationExplainer explainer:  57%|█████▋    | 67/117 [00:18<00:12,  4.00it/s]
PermutationExplainer explainer:  58%|█████▊    | 68/117 [00:19<00:12,  3.95it/s]
PermutationExplainer explainer:  59%|█████▉    | 69/117 [00:19<00:12,  3.94it/s]
PermutationExplainer explainer:  60%|█████▉    | 70/117 [00:19<00:12,  3.89it/s]
PermutationExplainer explainer:  61%|██████    | 71/117 [00:19<00:11,  3.85it/s]
PermutationExplainer explainer:  62%|██████▏   | 72/117 [00:20<00:11,  3.87it/s]
PermutationExplainer explainer:  62%|██████▏   | 73/117 [00:20<00:11,  3.92it/s]
PermutationExplainer explainer:  63%|██████▎   | 74/117 [00:20<00:10,  3.93it/s]
PermutationExplainer explainer:  64%|██████▍   | 75/117 [00:20<00:10,  3.94it/s]
PermutationExplainer explainer:  65%|██████▍   | 76/117 [00:21<00:10,  3.96it/s]
PermutationExplainer explainer:  66%|██████▌   | 77/117 [00:21<00:10,  3.90it/s]
PermutationExplainer explainer:  67%|██████▋   | 78/117 [00:21<00:10,  3.90it/s]
PermutationExplainer explainer:  68%|██████▊   | 79/117 [00:21<00:09,  3.89it/s]
PermutationExplainer explainer:  68%|██████▊   | 80/117 [00:22<00:09,  3.87it/s]
PermutationExplainer explainer:  69%|██████▉   | 81/117 [00:22<00:09,  3.89it/s]
PermutationExplainer explainer:  70%|███████   | 82/117 [00:22<00:08,  3.90it/s]
PermutationExplainer explainer:  71%|███████   | 83/117 [00:22<00:08,  3.89it/s]
PermutationExplainer explainer:  72%|███████▏  | 84/117 [00:23<00:08,  3.90it/s]
PermutationExplainer explainer:  73%|███████▎  | 85/117 [00:23<00:08,  3.89it/s]
PermutationExplainer explainer:  74%|███████▎  | 86/117 [00:23<00:07,  3.91it/s]
PermutationExplainer explainer:  74%|███████▍  | 87/117 [00:23<00:07,  3.92it/s]
PermutationExplainer explainer:  75%|███████▌  | 88/117 [00:24<00:07,  3.93it/s]
PermutationExplainer explainer:  76%|███████▌  | 89/117 [00:24<00:07,  3.93it/s]
PermutationExplainer explainer:  77%|███████▋  | 90/117 [00:24<00:06,  3.91it/s]
PermutationExplainer explainer:  78%|███████▊  | 91/117 [00:24<00:06,  3.86it/s]
PermutationExplainer explainer:  79%|███████▊  | 92/117 [00:25<00:06,  3.83it/s]
PermutationExplainer explainer:  79%|███████▉  | 93/117 [00:25<00:06,  3.84it/s]
PermutationExplainer explainer:  80%|████████  | 94/117 [00:25<00:05,  3.87it/s]
PermutationExplainer explainer:  81%|████████  | 95/117 [00:25<00:05,  3.89it/s]
PermutationExplainer explainer:  82%|████████▏ | 96/117 [00:26<00:05,  3.90it/s]
PermutationExplainer explainer:  83%|████████▎ | 97/117 [00:26<00:05,  3.91it/s]
PermutationExplainer explainer:  84%|████████▍ | 98/117 [00:26<00:04,  3.82it/s]
PermutationExplainer explainer:  85%|████████▍ | 99/117 [00:26<00:04,  3.86it/s]
PermutationExplainer explainer:  85%|████████▌ | 100/117 [00:27<00:04,  3.88it/s]
PermutationExplainer explainer:  86%|████████▋ | 101/117 [00:27<00:04,  3.90it/s]
PermutationExplainer explainer:  87%|████████▋ | 102/117 [00:27<00:03,  3.93it/s]
PermutationExplainer explainer:  88%|████████▊ | 103/117 [00:28<00:03,  3.92it/s]
PermutationExplainer explainer:  89%|████████▉ | 104/117 [00:28<00:03,  3.89it/s]
PermutationExplainer explainer:  90%|████████▉ | 105/117 [00:28<00:03,  3.90it/s]
PermutationExplainer explainer:  91%|█████████ | 106/117 [00:28<00:02,  3.87it/s]
PermutationExplainer explainer:  91%|█████████▏| 107/117 [00:29<00:02,  3.85it/s]
PermutationExplainer explainer:  92%|█████████▏| 108/117 [00:29<00:02,  3.94it/s]
PermutationExplainer explainer:  93%|█████████▎| 109/117 [00:29<00:02,  3.92it/s]
PermutationExplainer explainer:  94%|█████████▍| 110/117 [00:29<00:01,  3.89it/s]
PermutationExplainer explainer:  95%|█████████▍| 111/117 [00:30<00:01,  3.87it/s]
PermutationExplainer explainer:  96%|█████████▌| 112/117 [00:30<00:01,  3.91it/s]
PermutationExplainer explainer:  97%|█████████▋| 113/117 [00:30<00:01,  3.91it/s]
PermutationExplainer explainer:  97%|█████████▋| 114/117 [00:30<00:00,  3.93it/s]
PermutationExplainer explainer:  98%|█████████▊| 115/117 [00:31<00:00,  3.94it/s]
PermutationExplainer explainer:  99%|█████████▉| 116/117 [00:31<00:00,  3.91it/s]
PermutationExplainer explainer: 100%|██████████| 117/117 [00:31<00:00,  3.93it/s]
PermutationExplainer explainer: 118it [00:31,  3.92it/s]
PermutationExplainer explainer: 118it [00:31,  2.70it/s]

DONE: Pre_T2

====================================================================================================
Running: T2_ADC
Input: output/pairwise_datasets_report_only/T2_ADC_M1_pairwise.csv
Executed notebook: ./executed_pairwise_notebooks/T2_ADC_executed.ipynb
====================================================================================================

Executing:   0%|          | 0/59 [00:00<?, ?cell/s]

DONE: T2_ADC

BATCH FINISHED
Completed: ['Post1_ADC', 'Post1_Post2', 'Post1_T2', 'Post2_ADC', 'Post2_T2', 'Pre_ADC', 'Pre_Post1', 'Pre_Post2', 'Pre_T2', 'T2_ADC']
Failed: []